[package]
name = "lost_in_time"
version = "0.1.0"
authors = ["not_a_seagull <jtnunley01@gmail.com>"]
edition = "2018"

[dependencies]
lit-gl-wrapper = { path = "./lit-gl-wrapper" }
nalgebra = "0.21.0"
thiserror = "1"
